name: survey_flow
description: Onboarding/Survey flow manager for Flutter
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.0
  flutter_svg: ^2.0.3
  lottie: ^2.2.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter: